// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  database: {
    provider: "sqlite",
    url: "file:./prisma/dev.db", // local SQLite file
  },
  client: {
    generator: "prisma-client-js",
  },
  migrations: {
    path: "./prisma/migrations",
  },
});



